export enum ContentRiskCategory {
  TOXICITY = 'TOXICITY',
  HARASSMENT = 'HARASSMENT',
  HATE = 'HATE',
  THREAT = 'THREAT',
  SELF_HARM = 'SELF_HARM',
  SEXUAL_CONTENT = 'SEXUAL_CONTENT',
  SPAM = 'SPAM',
  SCAM = 'SCAM',
  MISINFORMATION = 'MISINFORMATION',
}
