export enum ContentRiskStepName {
  NORMALIZE_TEXT = 'NORMALIZE_TEXT',
  DETECT_DUPLICATE = 'DETECT_DUPLICATE',
  RUN_RULE_BASED_CHECKS = 'RUN_RULE_BASED_CHECKS',
  RUN_AI_ANALYSIS = 'RUN_AI_ANALYSIS',
  AGGREGATE_RESULT = 'AGGREGATE_RESULT',
}
