export enum ContentRiskStepName {
  VALIDATE_INPUT = 'VALIDATE_INPUT',
  NORMALIZE_TEXT = 'NORMALIZE_TEXT',
  SAVE_RAW_INPUT = 'SAVE_RAW_INPUT',
  RUN_RULE_BASED_CHECKS = 'RUN_RULE_BASED_CHECKS',
  DERIVE_RISK_LEVEL = 'DERIVE_RISK_LEVEL',
  SAVE_RESULT = 'SAVE_RESULT',
}
